In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

In [ ]:
dataset = pd.read_csv("/content/drive/My Drive/AI_ASSIGNMENT/roo_data (1).csv")

In [ ]:
dataset.loc[dataset['Suggested Job Role'].str.contains('Engineer', case=False), 'Suggested Job Role'] = 'Engineer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Analyst', case=False), 'Suggested Job Role'] = 'Analyst'
dataset.loc[dataset['Suggested Job Role'].str.contains('Administrator', case=False), 'Suggested Job Role'] = 'Manager'
dataset.loc[dataset['Suggested Job Role'].str.contains('Manager', case=False), 'Suggested Job Role'] = 'Manager'
dataset.loc[dataset['Suggested Job Role'].str.contains('Designer', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Developer', case=False), 'Suggested Job Role'] = 'Developer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Quality Assurance', case=False), 'Suggested Job Role'] = 'Technical Support'
dataset.loc[dataset['Suggested Job Role'].str.contains('Support', case=False), 'Suggested Job Role'] = 'Technical Support'
dataset.loc[dataset['Suggested Job Role'].str.contains('Architect', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Design & UX', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Information Technology Auditor', case=False), 'Suggested Job Role'] = 'Manager'

In [ ]:
print(dataset['Suggested Job Role'].unique())

['Developer' 'Manager' 'Analyst' 'Engineer' 'Designer' 'Technical Support']


In [ ]:
dataset[dataset.duplicated()]

Empty DataFrame
Columns: [Acedamic percentage in Operating Systems, percentage in Algorithms, Percentage in Programming Concepts, Percentage in Software Engineering, Percentage in Computer Networks, Percentage in Electronics Subjects, Percentage in Computer Architecture, Percentage in Mathematics, Percentage in Communication skills, Hours working per day, Logical quotient rating, hackathons, coding skills rating, public speaking points, can work long time before system?, self-learning capability?, Extra-courses did, certifications, workshops, talenttests taken?, olympiads, reading and writing skills, memory capability score, Interested subjects, interested career area, Job/Higher Studies?, Type of company want to settle in?, Taken inputs from seniors or elders, interested in games, Interested Type of Books, Salary Range Expected, In a Realtionship?, Gentle or Tuff behaviour?, Management or Technical, Salary/work, hard/smart worker, worked in teams ever?, Introvert, Suggested Job Role]
Index: []

In [ ]:
dataset['Suggested Job Role'].value_counts()

Manager              5181
Analyst              3874
Developer            3394
Engineer             2973
Designer             2319
Technical Support    2259
Name: Suggested Job Role, dtype: int64

In [ ]:
print(dataset.isna().sum())

Acedamic percentage in Operating Systems    0
percentage in Algorithms                    0
Percentage in Programming Concepts          0
Percentage in Software Engineering          0
Percentage in Computer Networks             0
Percentage in Electronics Subjects          0
Percentage in Computer Architecture         0
Percentage in Mathematics                   0
Percentage in Communication skills          0
Hours working per day                       0
Logical quotient rating                     0
hackathons                                  0
coding skills rating                        0
public speaking points                      0
can work long time before system?           0
self-learning capability?                   0
Extra-courses did                           0
certifications                              0
workshops                                   0
talenttests taken?                          0
olympiads                                   0
reading and writing skills        

In [ ]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

38

In [ ]:
dataset.iloc[:,14:38]

can work long time before system?  ... Introvert
0                                   yes  ...        no
1                                   yes  ...       yes
2                                   yes  ...       yes
3                                    no  ...       yes
4                                    no  ...       yes
...                                 ...  ...       ...
19995                               yes  ...        no
19996                               yes  ...       yes
19997                               yes  ...       yes
19998                                no  ...        no
19999                               yes  ...        no

[20000 rows x 24 columns]

In [ ]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  ...  public speaking points
0                                            69  ...                       8
1                                            78  ...                       3
2                                            71  ...                       3
3                                            76  ...                       5
4                                            92  ...                       3
...                                         ...  ...                     ...
19995                                        83  ...                       8
19996                                        80  ...                       8
19997                                        83  ...                       3
19998                                        68  ...                       5
19999                                        73  ...                       6

[20000 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
labelencoder = LabelEncoder()

In [ ]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [ ]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1]], dtype=object)

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
data1=data[:,:14]

In [ ]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [ ]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [ ]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [ ]:
df1 = np.append(normalized_data,data2,axis=1)

df1.shape

(20000, 38)

In [ ]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [ ]:
X1.head()

Acedamic percentage in Operating Systems  ... Introvert
0                                  0.28509  ...         0
1                                  0.34998  ...         1
2                                 0.295012  ...         1
3                                 0.328025  ...         1
4                                 0.397157  ...         1

[5 rows x 38 columns]

In [ ]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [ ]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   2
1                   4
2                   4
3                   4
4                   0

In [ ]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.1,random_state=10) 

In [ ]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [ ]:
print("confusion matrics=")
print(cm)
print("accuracy=",accuracy*100)

confusion matrics=
[[ 66  45  66  63 106  46]
 [ 49  23  47  37  58  34]
 [ 66  46  55  52  85  34]
 [ 48  35  57  40  79  41]
 [108  51  78  74 126  68]
 [ 50  27  31  33  49  27]]
accuracy= 16.85


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.17      0.17      0.17       392
           1       0.10      0.09      0.10       248
           2       0.16      0.16      0.16       338
           3       0.13      0.13      0.13       300
           4       0.25      0.25      0.25       505
           5       0.11      0.12      0.12       217

    accuracy                           0.17      2000
   macro avg       0.15      0.16      0.15      2000
weighted avg       0.17      0.17      0.17      2000

[[ 66  45  66  63 106  46]
 [ 49  23  47  37  58  34]
 [ 66  46  55  52  85  34]
 [ 48  35  57  40  79  41]
 [108  51  78  74 126  68]
 [ 50  27  31  33  49  27]]


In [ ]:
from sklearn import svm

In [ ]:
clf = svm.SVC()
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
svm_y_pred = clf.predict(X_test)

In [ ]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [ ]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[  0   0   0   0 392   0]
 [  0   0   0   0 248   0]
 [  0   0   0   0 338   0]
 [  0   0   0   0 300   0]
 [  0   0   0   0 505   0]
 [  0   0   0   0 217   0]]
  
accuracy= 25.25


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(learning_rate=1.75,n_estimators=300)
ada.fit(X_train, y_train)
y_ada = ada.predict(X_test)
ada_cm = confusion_matrix(y_test,y_ada)
ada_accuracy = accuracy_score(y_test,y_ada)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print("confusion matrics=",ada_cm)
print("  ")
print("accuracy=",ada_accuracy*100)

confusion matrics= [[ 44  18  36  24 254  16]
 [ 27  10  20   5 184   2]
 [ 46  19  28  13 227   5]
 [ 34   5  34  14 200  13]
 [ 67  16  44  30 334  14]
 [ 30   6  25  14 136   6]]
  
accuracy= 21.8


In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
y_mlp=clf.predict(X_test)
mlp_cm = confusion_matrix(y_test,y_mlp)
mlp_accuracy = accuracy_score(y_test,y_mlp)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print("confusion matrics=",mlp_cm)
print("  ")
print("accuracy=",mlp_accuracy*100)

confusion matrics= [[ 52  13  22  14 277  14]
 [ 37   7  10  12 174   8]
 [ 46   8  17  12 242  13]
 [ 38   5  23  17 206  11]
 [ 87   9  28  15 353  13]
 [ 31   5   8   8 150  15]]
  
accuracy= 23.05
